---
- name: initialize horcrux config (DBG - about to run these commands)
  debug:
    msg: "horcrux config init {{ lookup('template', 'signer_order.j2') }}"

- name: copy horcrux init script
  become: true
  template:
    src: 'signer_order.j2'
    dest: '{{ horcrux_dir }}/init_horcrux.sh'
    owner: '{{ horcrux_user }}'
    group: '{{ horcrux_user }}'
    mode: '0700'

- name: initializing horcrux config actual
  ansible.builtin.command: sudo su - "{{ horcrux_user }}" -c "{{ horcrux_dir }}/init_horcrux.sh"
  become: true

- name: Copy keys
  become: true
  ansible.builtin.copy:
    src: "keys/private_share_{{ signorder }}.json"
    dest: "{{ horcrux_dir }}/.horcrux/share.json"
    owner: "{{ horcrux_user }}"
    group: "{{ horcrux_user }}"
    mode: '0400'